class Lorem
  TEXTS = [
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacus turpis, consequat quis dignissim at, ultrices a orci. Phasellus scelerisque, ligula a dignissim euismod, arcu eros elementum felis, id ultricies arcu arcu vel risus. Aliquam sit amet nunc ipsum, quis ultricies arcu. Suspendisse consequat congue enim, vel rhoncus risus rhoncus nec. Nunc vulputate consequat dignissim. Pellentesque fringilla neque vel leo consectetur in dictum ante blandit. Nulla sed nisi sit amet dolor vehicula vestibulum vel congue metus. Duis in metus sit amet lorem ultricies convallis eu in diam. Proin eget neque eu tellus posuere rutrum. Praesent metus enim, ullamcorper eu suscipit et, viverra vel nibh. Aliquam nulla metus, vulputate vitae faucibus eget, tempor ut enim.",

           "Vivamus a quam arcu. Sed vitae elit vitae libero tristique malesuada. Vivamus id sollicitudin mauris. Nunc ut arcu eget erat auctor dapibus a id nisl. Duis ultricies augue eget eros tincidunt ac consequat mauris scelerisque. Duis blandit lectus eu mi tempus commodo. In ultrices velit nisl. Suspendisse eu nisl eros, id euismod ante. Donec eget justo in erat porttitor tempor. Curabitur tempor metus purus. Sed ut sapien ac ipsum venenatis mattis a non nibh. Aenean egestas sollicitudin sapien, eu hendrerit metus porta at. Ut egestas libero posuere eros facilisis nec convallis velit imperdiet. Suspendisse rhoncus leo neque. Cras tempor porta aliquet. Nulla non dui orci, nec hendrerit lectus. Pellentesque tincidunt bibendum iaculis. Ut iaculis tempor purus, imperdiet varius turpis aliquam ut. Donec urna nisl, molestie non ultricies sit amet, semper non elit.",

           "Cras placerat lobortis quam facilisis pharetra. Maecenas vel odio in libero commodo accumsan. Sed lacinia enim vel nisl dictum venenatis. Curabitur erat dui, aliquam et sollicitudin nec, facilisis ac nisl. Etiam est ipsum, porttitor nec fermentum et, laoreet ut neque. Nunc orci lectus, euismod eget hendrerit ac, porttitor eu erat. Etiam id dolor elit. In consequat fringilla suscipit. Mauris a eros non urna rhoncus eleifend non at magna. Nulla facilisis, orci ut venenatis placerat, nisl orci semper erat, et interdum est nulla a libero. Sed sed nunc id erat dignissim blandit.",

           "Proin urna tellus, egestas sed accumsan ac, consequat ut sapien. Sed rutrum, risus ac sollicitudin blandit, lectus ante interdum mauris, vitae egestas ipsum lacus vitae justo. Quisque scelerisque tincidunt purus, eget auctor tortor dapibus luctus. Fusce ut erat eu nibh faucibus gravida. Suspendisse rutrum velit dui, et accumsan libero. Pellentesque sollicitudin odio ut dolor auctor non adipiscing turpis egestas. Vivamus mattis, orci ut vestibulum fringilla, sem tellus pellentesque nulla, quis vehicula nisl arcu sed lectus. Aenean vitae turpis massa, nec vestibulum lacus. Aliquam erat volutpat. Sed suscipit condimentum commodo. Ut faucibus convallis auctor. Donec et turpis eu nibh dignissim pharetra at vel libero. Nullam egestas mauris gravida nibh viverra quis ullamcorper tortor cursus. Fusce orci ligula, mattis sed pellentesque ac, sagittis ac augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse venenatis arcu ac purus ullamcorper ac iaculis lorem tincidunt.",
           "Nulla facilisi. Integer purus dui, rutrum non fermentum eu, tempor nec enim. Nam velit purus, rhoncus in lacinia aliquam, interdum eget nulla. Cras in libero ante, ut ornare quam. Praesent eu augue mauris, id mollis metus. Praesent odio odio, rutrum sit amet auctor elementum, tempus eu felis. Sed hendrerit aliquam nulla, ac malesuada erat gravida ac. Duis sed est nisl, nec laoreet sem. Vestibulum et erat nulla. Suspendisse pellentesque, neque ut iaculis mattis, dolor leo faucibus enim, sed euismod velit tellus ut arcu. Phasellus mi est, dapibus vitae mollis id, rhoncus vitae augue. Sed vel magna quis felis pellentesque sagittis ut eget mauris. Sed turpis magna, euismod sit amet condimentum et, tincidunt vitae nisi. Cras molestie, ante ac ultrices aliquet, felis turpis molestie nisl, sit amet sagittis felis eros non ligula."
          ]
  @@spin = 0
  def self.next
    desc = TEXTS[0-@@spin]
    @@spin -= 1
    desc
  end
end
